### ISSUE TITLE
Failed get parallel run logs

### ISSUE THREAD

**Issue by dreyk** [kuberlab/python-mlboardclient#3]
2018-03-14 17:10:52,334 INFO       mlboardclient.api.v2.tasks [-] Completed task train:11 with status=Succeeded
Traceback (most recent call last):
  File "hparameter1.py", line 67, in <module>
    main()
  File "hparameter1.py", line 61, in main
    logs = task.parallel_run(2, jobs(7))
  File "/notebooks/lib/mlboardclient/api/v2/tasks.py", line 185, in parallel_run
    for i, t in builds.items():
RuntimeError: dictionary changed size during iteration

**Comment by nmakhotkin** [comment]
Ack. It only reproduces on Python 3.x

**Comment by nmakhotkin** [comment]
Fixed in https://github.com/kuberlab/python-mlboardclient/commit/1add4a72cd3f15a8b1b5e94353767b9c6253e583
